package com.shyaragas.app.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;
import java.util.List;

@DynamoDBTable(tableName = "ShyaraGasClients")
public class Client implements Serializable {

	private String name;
	private String lastname;
	private String email;
	private List<Vehicle> vehiclelist;
	private String phonenumber;
	private String id;
	private int dni;

	public Client(String name, String lastname, String email, List vehiclelist, String phonenumber, String id, int dni)
	{
		this.name = name;
		this.lastname = lastname;
		this.email = email;
		this.vehiclelist = vehiclelist;
		this.phonenumber = phonenumber;
		this.id = id;
		this.dni = dni;
	}

	public Client()
	{

	}



	@DynamoDBHashKey(attributeName = "id")//@DynamoDBAttribute annotation is optional when the name of the DynamoDB attribute matches the name of the property declared in the class. When they differ, use this annotation with the attributeName() parameter to specify which DynamoDB attribute this property corresponds to.
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "name")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "lastname")
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@DynamoDBAttribute(attributeName = "email")
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

	@DynamoDBIgnore
	public List getVehiclelist()
	{
		return vehiclelist;
	}
	public void setVehiclelist(List<Vehicle> vehiclelist)
	{
		this.vehiclelist = vehiclelist;
	}

	@DynamoDBAttribute(attributeName = "dni")
	public int getDni() {
		return dni;
	}
	public void setDni(int dni) {
		this.dni = dni;
	}

	@DynamoDBAttribute(attributeName = "phonenumber")
	public String getPhonenumber() {
		return phonenumber;
	}
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}
}
