package com.shyaragas.app.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "ShyaraGasVehicles")
public class Vehicle
{
    private String id;
    private String clientId;
    private String brand;
    private String model;
    private String plate;
    private String problems;
    private String features;

    public Vehicle(String id, String clientId, String model, String brand, String plate, String problems, String features)
    {
        this.id = id;
        this.clientId = clientId;
        this.model = model;
        this.brand = brand;
        this.plate = plate;
        this.problems = problems;
        this.features = features;
    }

    public Vehicle()
    {

    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId()
    {
        return id;
    }
    public void setId(String id)
    {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "clientId")
    public String getClientId()
    {
        return clientId;
    }
    public void setClientId(String clientId)
    {
        this.clientId = clientId;
    }

    @DynamoDBAttribute(attributeName = "brand")
    public String getBrand()
    {
        return brand;
    }
    public void setBrand(String brand)
    {
        this.brand = brand;
    }

    @DynamoDBAttribute(attributeName = "model")
    public String getModel()
    {
        return model;
    }
    public void setModel(String model)
    {
        this.model = model;
    }

    @DynamoDBAttribute(attributeName = "plate")
    public String getPlate()
    {
        return plate;
    }
    public void setPlate(String plate)
    {
        this.plate = plate;
    }

    @DynamoDBAttribute(attributeName = "problems")
    public String getProblems()
    {
        return problems;
    }
    public void setProblems(String problems)
    {
        this.problems = problems;
    }

    @DynamoDBAttribute(attributeName = "features")
    public String getFeatures()
    {
        return features;
    }
    public void setFeatures(String features)
    {
        this.features = features;
    }
}
